### ISSUE TITLE
Web page error 500 when clicking on the button "Set first port" with self-made device template in version 21.01

### ISSUE THREAD

**Issue by Pergravis** [opendcim/openDCIM#1285]
OS System: CentOS Stream release 8
openDCIM Version: 21.01
The error (division by zero) points to the file in the directory classes/Device.class.php to line 2244.

**Comment by wilpig** [comment]
Odds are you have an invalid picture set in your device template.

https://github.com/opendcim/openDCIM/blob/master/classes/Device.class.php#L2244

**Comment by Pergravis** [comment]
Hello Mr. Wongwisch,
many many thanks for your quick response!
I'll try this tomorrow morning at 9am CET and give you feedback!

Best regards from Krefeld in Germany
Volker Minor

Wilbur Longwisch ***@***.***> schrieb am Mi., 11. Aug. 2021,
14:48:

**Comment by Pergravis** [comment]
Hello Mr. Wongwisch,
I have used SVG images and now changed them to PNG.
With this it works!
Is it planned to use SVG images in openDCIM in the future?
Thanks again
