### ISSUE TITLE
Device not visible in cabinet

### ISSUE THREAD

**Issue by SerhatCal** [opendcim/openDCIM#1293]
When we go inside the cabinet, we see a green icon. You can see in the attachment. I add a device, but it does not appear in the cabinet. The percentage changes on the space side. How can I see the device? can you help me?

![opendcim](https://user-images.githubusercontent.com/91000816/133960978-38a8afae-2d7b-4eb6-8eb0-86cb8074c63e.JPG)
.

**Comment by samilliken** [comment]
This is what the mailing list is for - answering this question, which has been answered many times, already.    Your OS likely doesn't have a default timezone, so PHP needs you to set it in the global php.ini file.
