### ISSUE TITLE
Allow the insertion of half width device.

### ISSUE THREAD

**Issue by bodypheo** [opendcim/openDCIM#1297]
Hello,
thank you very much for your effort on developing opendcim. I would like to ask if it is possible or would it be possible to add a half width device, so for example in one unit I can have to half width fiber switch.
Thank you very much
Kind regards

**Comment by timlegge** [comment]
The easiest method is to define  a chassis with a right and left half and
insert the half width switch in it.

Tim

**Comment by samilliken** [comment]
There is also the predefined case of a shelf.

Scott
