### ISSUE TITLE
SVG crashes OpenDCIM

### ISSUE THREAD

**Issue by rvtis** [opendcim/openDCIM#1298]
I uploaded an SVG map successfully, but when I tried to check out the datacenter, the page crashes. It crashes every time.

opendcim is currently unable to handle this request.
HTTP ERROR 500

**Comment by wilpig** [comment]
Don't use svg

**Comment by wilpig** [comment]
Looking at the code, make sure you have php_xml available.

https://github.com/opendcim/openDCIM/blob/master/dc_stats.php#L92

**Comment by samilliken** [comment]
Dangit, Wilpig beat me to the "don't use svg" response

**Comment by wilpig** [comment]
Never heard anything back, assuming it was php-xml related.
