### ISSUE TITLE
Devices won't show in Cabinets

### ISSUE THREAD

**Issue by ducppscb** [opendcim/openDCIM#1300]
Hello,

I have installed OpenDCIM on CentOS 7, I can add new DataCenters, Cabinets, even Devices into Cabinets, but neither the labels nor the pictures of the devices will show on cabnavigator. The green square keep on rotating. The device entries can be found running a search.
Fixed
1. Solution 1
Edit /opt/openDCIM/opendcim/scripts/common.js

$.ajax({url: 'api/v1/cabinet/'+cabid+'/getpictures',type: "get",async: true,success: function(data){
window.pictures[cabid]=data.pictures;
cab_picture_count++;
}
});

-> change that async: true to async: false

2. Solution 2
Edit php.ini
Modify your php.ini file and search for 'max_execution_time' - changed to double it.

But not run!!!
![image](https://user-images.githubusercontent.com/99798745/154241534-786822d4-4d3d-41d3-854e-0668609be1d9.png)

**Comment by DarlithRolin** [comment]
How did you fixed it?

**Comment by samilliken** [comment]
Install 23.04
