### ISSUE TITLE
Admin Own Devices allows unassigned rack editing

### ISSUE THREAD

**Issue by rvtis** [opendcim/openDCIM#1302]
As I was doing Admin Own Devices permission testing, I found out that a user with Admin Own Devices rights can do anything in an unassigned (General Use) rack except delete the rack. I tested on my end with an account that only has Global read and Admin Own Devices rights, nothing else. This flaw makes it more like a "Admin Own and Ownerless Devices" right than just your own stuff.
This, i think, should not be possible.

Please comment if it's intentional, and if not, please fix it.

**Comment by rvtis** [comment]
![image](https://user-images.githubusercontent.com/47510851/165056993-61b2913c-610e-4b91-8591-44489b76e045.png)

Made a usage rights matrix

**Comment by wilpig** [comment]
Yes.  Not assigned to a group = assigned to everyone.  The rights assignments in the database are not that granular and would have to be changed out to add a new table supporting a many to many model to calculate rights.
