### ISSUE TITLE
Updated 19.01 to 21.01 missing devices in Cabinets

### ISSUE THREAD

**Issue by psaletsr** [opendcim/openDCIM#1304]
Hi All,

Great product, I updated opendcim from 19.01 to 21.01. Everything looked good except the cabinets do not show any images. 
All I get is the rotating block. I can search on a device and it will find it. As a test I was able to move the device to another RU (I didn't) but is shows the the other locations on devices in the cabinet.

I have searched the archives and found some ideas, tried them, but didn't work. 
i.e.     updated image management. success
         updated php.ini as timezone was not set. I set timezone set as America/LosAngeles

any help is appreciated
thanks

**Comment by gmollygreen** [comment]
Problem schon gelöst? Eventuell im Template Management "Rebuild Image Cache" ausführen. Das hat bei mir damals das Problem gelöst.

**Comment by wilpig** [comment]
Problem older than a year, please send any future support related issues to the mailing list.
