### ISSUE TITLE
"$this" can no longer be used in a plain function or method since PHP 7.1 - possibly false positive?

### ISSUE THREAD

**Issue by spezialist1** [opendcim/openDCIM#1335]
I would like to draw attention to the following:

FILE: classes/Tags.class.php
-----------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
-----------------------------------------------------------------------------------------
 60 | ERROR | "$this" can no longer be used in a plain function or method since PHP 7.1.
 77 | ERROR | "$this" can no longer be used in a plain function or method since PHP 7.1.
-----------------------------------------------------------------------------------------

I have carefully analyzed the PHP code and came to the conclusion that this is probably a false positive issue. Does anyone have anything else to say about this?

**Comment by samilliken** [comment]
@spezialist1 since these are static defined methods, the $this context is actually valid here.   The warning is that for methods not defined as static, you'd get a fatal error, but that has been the case since PHP 5.

Reference:  https://wiki.php.net/rfc/this_var
