### ISSUE TITLE
Update jquery/jquery-ui to modern versions: the list of tooltips in the Configuration is no longer displayed

### ISSUE THREAD

**Issue by spezialist1** [opendcim/openDCIM#1336]
After [Update jquery/jquery-ui to modern versions](https://github.com/opendcim/openDCIM/commit/ddd835fdb2b64c9b27e027c65d5c44ef1f70546e) was applied, the list of tooltips in the Configuration is no longer displayed (see my screenshot):
![ToolTips_noview](https://user-images.githubusercontent.com/10425179/185344380-b9e97aaf-8d05-4d68-ba03-ca7e5c4d3477.jpg)

A temporary fix for this bug -- change the soft link `jquery.min.js -> jquery-1.11.2.min.js` to an older version of jquery v1.11.2.

**Comment by spezialist1** [comment]
@samilliken?..

**Comment by samilliken** [comment]
@wilpig just verified that this is still an issue
