### ISSUE TITLE
PHP Fatal error:  Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in classes/Device.class.php on line 369

### ISSUE THREAD

**Issue by JShaharov** [opendcim/openDCIM#1350]
Started getting this error while trying to access any racks

**Comment by samilliken** [comment]
This is because you are running PHP 8.x and the current release only supports through PHP 7.x.   The next release (23.01) will support PHP 8.
