### ISSUE TITLE
@$_SESSION['datacenters']=DataCenter::GetDCList(true)

### ISSUE THREAD

**Issue by RoyyZoy** [opendcim/openDCIM#1354]
Hello,
When I'm getting to this line:
@$_SESSION['datacenters']=DataCenter::GetDCList(true)
The page just stuck. No error message or something, Just blank page. If put "true" on the right side, It continue.
(I have prints before and after this line. So I can see that this is exactly the problematic line).

What is this "DataCenter::GetDCList(true)"  ?  why does it stop there?
Thanks.

**Comment by wilpig** [comment]
https://github.com/opendcim/openDCIM/blob/master/classes/DataCenter.class.php#L265
