### ISSUE TITLE
initial setup shows only report

### ISSUE THREAD

**Issue by xoroz** [opendcim/openDCIM#1357]
Dear everyone

I am over one hour looking for a solution to setup the openDCIM
I have it all configured as the guided instructions and install.php sees no error.

I delete install.php but still see only Report (no menus)
same as https://github.com/opendcim/openDCIM/issues/1145

I run on Centos 8 latest version 21
DB seems missing

MariaDB [dcim]>  select * from fac_User;
ERROR 1146 (42S02): Table 'dcim.fac_User' doesn't exist

How can I fix it?

Thank you

**Comment by xoroz** [comment]
no help? anyone ?
Should I try to reinstall ?

**Comment by samilliken** [comment]
Per the instructions on the website at https://opendcim.org you are to send questions to the mailing list, not here.   This is for tracking bugs, not playing Helpdesk.
