### ISSUE TITLE
Supposed bug fix in dc_stats.php produces new bug in release 23.01

### ISSUE THREAD

**Issue by karig** [opendcim/openDCIM#1361]
Refers to: https://github.com/opendcim/openDCIM/commit/a942c238ad811d97555d9a50c72cef686d0ca8e2

**dc_stats.php** (version 21.01): 
`$mapHTML="<div class=\"canvas\" style=\"background-image: url('".$mapfile."')\">`

My output:
`<div class="canvas" style="background-image: url('assets/drawings/my_dc_map.jpg')">`

That works for me in openDCIM-21.01 (php7) and also in openDCIM 23.01 (php8).

**dc_stats.php** (version 23.01 with urlencode): 
`$mapHTML="<div class=\"canvas\" style=\"background-image: url('".urlencode($mapfile)."')\">`

My output:
`<div class="canvas" style="background-image: url('assets%2Fdrawings%2Fmy_dc_map.jpg')">`

→ My DC map files will not be shown.

Please revert this commit.

**Comment by wilpig** [comment]
That was put in as mitigation for a code injection problem and handle paths that people put quotes into.  You have something on your system that is blocking the translation in the browser.  You can check the dev site here on RHEL8 with PHP8  http://dev.opendcim.org/dc_stats.php?dc=1  

```
<div class="canvas" style="background-image: url('nest1%2Fnest2%2Fdra%27ings%2Fexample.png')">
```
That path is translated just fine into 
```
https://dev.opendcim.org/nest1%2Fnest2%2Fdra%27ings%2Fexample.png
```

What error are you getting in the web server log when you try to goto that path?

**Comment by wilpig** [comment]
What browser are you using?  Any javascript blocking?  I've tested on Safari, Chrome, and Firefox and all three render that page just fine.

**Comment by karig** [comment]
Hi @wilpig,

I use Firefox 113.02, but I am getting the Error 404 (not found) also with Chrome and curl, and also with your example:

`https://dev.opendcim.org/nest1%2Fnest2%2Fdra%27ings%2Fexample.png`

With `/` instead of `%2F` it works.

In all other cases of `background-image` in openDCIM is also `/` used. It is only a problem with the Data Center map code line changed in https://github.com/opendcim/openDCIM/commit/a942c238ad811d97555d9a50c72cef686d0ca8e2.

**Comment by Tarot67** [comment]
I have the same issue. in log:

[31/May/2023:14:18:46 +0200] "GET /drawings%2FdatacenterISIS.png HTTP/1.1" 404 488 "http://127.0.0.1/dc_stats.php?dc=1" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0"

**Comment by Tarot67** [comment]
And effectivly there are %2F in path and i have no picture under my datacenter.

But the opendcim 23.01 work well ;) i tested new route PUT deviceport it is great!

thank for all

**Comment by karig** [comment]
Yes, that solves the problem.

**Comment by wilpig** [comment]
https://github.com/opendcim/openDCIM/wiki/FAQ

Added a new page to the wiki for this.
