### ISSUE TITLE
Background image is not displayed on the dc_stats.php page

### ISSUE THREAD

**Issue by insiac** [opendcim/openDCIM#1371]
Background image is not displayed on the dc_stats.php page.
This is due to line: https://github.com/opendcim/openDCIM/blob/4a17818f90bdb15596bdb7ec7b5473baccec4d8d/dc_stats.php#L89 `urlencode($mapfile)` encodes both the path and the file name of the file name that were concatenated in to $mapfile at line https://github.com/opendcim/openDCIM/blob/4a17818f90bdb15596bdb7ec7b5473baccec4d8d/dc_stats.php#L99 Because the path contains a "/", after url encoding the "/' becomes "%2F" making the image location invalid: 
For example: 
`urlencode("drawings/background1.png") --> "drawings%2Fbackground1.png"`
As per php mnual (https://www.php.net/manual/en/function.urlencode.php): 
"This function is convenient when encoding a string to be used in a query part of a URL."

This could be fixed by removing the urlencode from the whole path:
`$mapHTML="<div class=\"canvas\" style=\"background-image: url('".$mapfile."')\">`
and only encoding the file name: 
`$mapfile=$config->ParameterArray["drawingpath"] . urlencode($dc->DrawingFileName);`

**Comment by samilliken** [comment]
This was already addressed in https://github.com/opendcim/openDCIM/discussions/1364
