### ISSUE TITLE
Unable to edit coordinates for Chassis slots

### ISSUE THREAD

**Issue by packetmickey** [opendcim/openDCIM#1374]
After initial creation of a "chassis" device type template, the edit coordinates button is presented. When selecting this option, no dialog or other action takes place.
I have been able to replicate this on the demo,opendcim.org server as well as my installation.

**Comment by packetmickey** [comment]
Uncaught ReferenceError: drawSlots is not defined
    <anonymous> https://demo.opendcim.org/device_templates.php?TemplateID=15:288
    jQuery 7
    <anonymous> https://demo.opendcim.org/device_templates.php?TemplateID=15:289
    jQuery 13

This when displaying developer tools in the browser.

**Comment by packetmickey** [comment]
Sorry realized expanding the error might be more helpful.

Uncaught ReferenceError: drawSlots is not defined
    <anonymous> https://demo.opendcim.org/device_templates.php?TemplateID=15:288
    jQuery 7
        dispatch
        handle
        trigger
        trigger
        each
        each
        trigger
    <anonymous> https://demo.opendcim.org/device_templates.php?TemplateID=15:289
    jQuery 13
        e
        t
        setTimeout handler*Deferred/then/l/<
        c
        fireWith
        fire
        c
        fireWith
        ready
        B
        EventListener.handleEvent*
        <anonymous>
        <anonymous>

**Comment by wilpig** [comment]
Related to #1373
