### ISSUE TITLE
Possible documentation error regarding using nginx and rewrite

### ISSUE THREAD

**Issue by pentiumoverdrive** [opendcim/openDCIM#1438]
When you setup opendcim using nginx, the preflight page suggests that you set up the following rewrites:

```
    location ~ ^/opendcim/api/v1 {
        rewrite ^(.*) /opendcim/api/v1/index.php last;
    }
    location ~ ^/opendcim/api/test {
        rewrite ^(.*) /opendcim/api/test/index.php last;
    }
```
But opendcim is the document root already, so the preflight only passes if you use something like this:

```
  location ~ ^/api/v1 {
        rewrite ^(.*) /api/v1/index.php last;
    }
    location ~ ^/api/test {
        rewrite ^(.*) /api/test/index.php last;
    }

```

**Comment by wilpig** [comment]
It's not evaluating the path and just adding a suggestion.  What is shown is an example.  Nothing to fix.
