### ISSUE TITLE
Patch panel to Server, Device Port not clickable

### ISSUE THREAD

**Issue by pentiumoverdrive** [opendcim/openDCIM#1454]
Running latest, "Device Port" selection on a patch panel seems broken on the demo site as well as my local install:
<img width="406" alt="image" src="https://github.com/opendcim/openDCIM/assets/17021956/d0bbca1d-7be7-4556-9924-a34dff61ca46">

The drop down works, but nothing is clickable if you try to connect a server from the patch panel.
Server to patch panel works fine.

No errors are logged.

**Comment by wilpig** [comment]
You already reported this and it was fixed in #1448

**Comment by pentiumoverdrive** [comment]
> You already reported this and it was fixed in #1448

That one was fixed sure, but this is not the same.

**Comment by wilpig** [comment]
This is specific to patch panels somehow, but i've narrowed it down to the color attribute that we don't use for patch panels and this line.

https://github.com/opendcim/openDCIM/blob/master/scripts/common.js#L2735
