### ISSUE TITLE
Error 500 on Outage Simulator report

### ISSUE THREAD

**Issue by calvaradESU** [opendcim/openDCIM#1457]
When I try to run an Outage Simulator report I get the following error:

[Tue Oct 10 08:35:52.148827 2023] [php:error] [pid 1177668] [client 10.222.24.44:61098] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/openDCIM-23.02/report_outage_simulator.php:166\nStack trace:\n#0 {main}\n  thrown in /var/www/openDCIM-23.02/report_outage_simulator.php on line 166, referer: https://dcim.emporia.edu/report_outage_simulator.php

It happens on the demo site too.

**Comment by samilliken** [comment]
I' m not getting the error 500 on the demo site, even when I neglect to select any power panels/sources that are out.   Closing this due to inability to replicate.   It may have been fixed in 23.04, which is what is now running on the demo site.
