### ISSUE TITLE
23.04: datacenter drawing not loaded (URL incorrect?)

### ISSUE THREAD

**Issue by jouvin** [opendcim/openDCIM#1465]
I just upgraded our openDCIM instance from 21.01 to 23.04. Everything seems fine except that the datacenter drawings (we have 2, both with the same issue) are not displayed when we click on a datacenter, despite when editing the datacenter the drawing is defined and properly rendered. There is no error in Apache logs but the access log displays a strange URL when trying to get/display the drawing (`/` is replaced by `%2F`):

> "GET /assets%2Fdrawings%2FBat._206_-_20220415.png HTTP/1.1"

This doesn't happen with other GET related to openDCIM...

**Comment by wilpig** [comment]
https://github.com/opendcim/openDCIM/wiki/FAQ#getting-404-trying-to-access-some-linksimages
