### ISSUE TITLE
İnstallation 

### ISSUE THREAD

**Issue by thecicek** [opendcim/openDCIM#1467]
Hello everyone 
I am installing version 23.04 on centos 7 with the instructions on https://wiki.opendcim.org/wiki/index.php/Installation but I can't reach the web page after installation. I installed version 4.0.1 with these instructions and reached the web page. Please help if there is an updated instruction?

**Comment by wilpig** [comment]
Wont' work since you need PHP8.  https://github.com/opendcim/openDCIM/wiki/RHEL
