### ISSUE TITLE
Composite View of Cabinets

### ISSUE THREAD

**Issue by vlozada** [opendcim/openDCIM#1474]
Composite View of Cabinets does not show the image. DCIM version 23.04

![image](https://github.com/opendcim/openDCIM/assets/19579838/c62bdc9c-0675-4ef6-a707-10726a282c54)

**Comment by vlozada** [comment]
Please can u help me???

**Comment by samilliken** [comment]
Not until you learn how to read the FAQ, where the answer to this would be.

**Comment by vlozada** [comment]
But the trouble is only there. the cabinets are OK...
![image](https://github.com/opendcim/openDCIM/assets/19579838/9d041a3c-f6b0-4c9f-a103-657e19d8e247)
just in the Composite View of Cabinets does not show the map of data center...
also the containet viewer are ok....
![image](https://github.com/opendcim/openDCIM/assets/19579838/b99b46c2-d28e-4ab0-84a0-7247ff4c56ad)

**Comment by vlozada** [comment]
pleaseeeeeeeeeeeeeee
:)

**Comment by wilpig** [comment]
https://github.com/opendcim/openDCIM/wiki/FAQ

**Comment by vlozada** [comment]
Thanks i try this =)

**Comment by vlozada** [comment]
Hi,

IT does' not work 🙁


[cid:786ac402-757d-47d1-9eb8-25f8e0a632c2]

ISC. Vicente Lozada Curiel

Administrador y Programador de Sistemas

TEL: 771 7176 710     |      IP: 330028      |      Correo: ***@***.***

Dirección: Carretera San Juan Tilcuautla Km 5, San Agustin Tlaxiaca, 42160

INE-DERFE-DITA
[cid:b51acb4e-c9dc-499f-8a14-6c30401e771b]
FAVOR DE NO IMPRIMIR ESTE CORREO, AMENOS QUE SEA REALMENTE NECESARIO.
________________________________
De: Wilbur Longwisch ***@***.***>
Enviado: lunes, 30 de octubre de 2023 05:47 p. m.
Para: opendcim/openDCIM ***@***.***>
Cc: LOZADA CURIEL VICENTE ***@***.***>; Author ***@***.***>
Asunto: Re: [opendcim/openDCIM] Composite View of Cabinets (Issue #1474)


https://github.com/opendcim/openDCIM/wiki/FAQ

**Comment by wilpig** [comment]
I assure you that mot definitely does work.  If you are still having issues then you will need to troubleshoot what error you are seeing the webserver logs.

https://github.com/opendcim/openDCIM/wiki/RHEL
https://github.com/opendcim/openDCIM/wiki/Ubuntu
https://github.com/opendcim/openDCIM/wiki/OpenSUSE

Make sure that your environment has been set up correctly by following the appropriate installation guide as well.

**Comment by vlozada** [comment]
tanks for u support,

My environment is RHEL 9, i have 5 years using this wonderful tool, and i make the upgrades.
This is the first time what i have this trouble. everything is ok, excep the CPD maps (i have two CPD).

I follow https://github.com/opendcim/openDCIM/wiki/RHEL and
https://wiki.opendcim.org/wiki/index.php/Upgradeto for my installation and my upgrade.

[cid:59643466-cc6d-49e1-a494-d5e4ee9d94c0] [cid:75d666df-fe77-4601-b6c1-0677a395642c]

Thansk,


[cid:458c72d6-90aa-498e-add0-32e85e7c4ad7]

ISC. Vicente Lozada Curiel

Administrador y Programador de Sistemas

TEL: 771 7176 710     |      IP: 330028      |      Correo: ***@***.***

Dirección: Carretera San Juan Tilcuautla Km 5, San Agustin Tlaxiaca, 42160

INE-DERFE-DITA
[cid:6443a2a9-bcfa-4bc1-8836-e5df7a56c8f4]
FAVOR DE NO IMPRIMIR ESTE CORREO, AMENOS QUE SEA REALMENTE NECESARIO.
________________________________
De: Wilbur Longwisch ***@***.***>
Enviado: lunes, 6 de noviembre de 2023 01:14 p. m.
Para: opendcim/openDCIM ***@***.***>
Cc: LOZADA CURIEL VICENTE ***@***.***>; Author ***@***.***>
Asunto: Re: [opendcim/openDCIM] Composite View of Cabinets (Issue #1474)


I assure you that mot definitely does work. If you are still having issues then you will need to troubleshoot what error you are seeing the webserver logs.

https://github.com/opendcim/openDCIM/wiki/RHEL
https://github.com/opendcim/openDCIM/wiki/Ubuntu
https://github.com/opendcim/openDCIM/wiki/OpenSUSE

Make sure that your environment has been set up correctly by following the appropriate installation guide as well.

**Comment by wilpig** [comment]
https://github.com/opendcim/openDCIM/wiki/RHEL#add-a-virtual-host-for-opendcim-1

If you followed this then you should have the encode slashes in your config.  If that is there and you are still having issues then you will need to look at your apache logs and see what the error is.

**Comment by vlozada** [comment]
Thanks fou u help,

I found the problem, Apache certificates was expired, i requested a new, install it and restart apache. Now everything is ok

Realy thanks. Regards.


[cid:929cda2e-0003-4a41-a000-852778d85cbb]

ISC. Vicente Lozada Curiel

Administrador y Programador de Sistemas

TEL: 771 7176 710     |      IP: 330028      |      Correo: ***@***.***

Dirección: Carretera San Juan Tilcuautla Km 5, San Agustin Tlaxiaca, 42160

INE-DERFE-DITA
[cid:c021d050-886c-4bf7-8db5-ce67434daef2]
FAVOR DE NO IMPRIMIR ESTE CORREO, AMENOS QUE SEA REALMENTE NECESARIO.
________________________________
De: Wilbur Longwisch ***@***.***>
Enviado: lunes, 6 de noviembre de 2023 06:58 p. m.
Para: opendcim/openDCIM ***@***.***>
Cc: LOZADA CURIEL VICENTE ***@***.***>; Author ***@***.***>
Asunto: Re: [opendcim/openDCIM] Composite View of Cabinets (Issue #1474)


https://github.com/opendcim/openDCIM/wiki/RHEL#add-a-virtual-host-for-opendcim-1

If you followed this then you should have the encode slashes in your config. If that is there and you are still having issues then you will need to look at your apache logs and see what the error is.
