### ISSUE TITLE
Data Center drawings not showing up in dc_stats.php

### ISSUE THREAD

**Issue by CharlesCraigDell** [opendcim/openDCIM#1475]
on line 106 in dc_stats.php 
$mapHTML="<div class=\"canvas\" style=\"background-image: url('".urlencode($mapfile)."')\">
.urlencode breaks the drawing path in the code.  fix is to change the line to 
$mapHTML="<div class=\"canvas\" style=\"background-image: url('$mapfile')\">

**Comment by wilpig** [comment]
https://github.com/opendcim/openDCIM/wiki/FAQ

**Comment by CharlesCraigDell** [comment]
Thanks.  Might want to add that to the install directions.

**Comment by wilpig** [comment]
You mean like right here?  

https://github.com/opendcim/openDCIM/wiki/RHEL#add-a-virtual-host-for-opendcim
https://github.com/opendcim/openDCIM/wiki/RHEL#add-a-virtual-host-for-opendcim-1
https://github.com/opendcim/openDCIM/wiki/Ubuntu#add-a-virtual-host-for-opendcim
https://github.com/opendcim/openDCIM/wiki/OpenSUSE#add-a-virtual-host-for-opendcim

**Comment by CharlesCraigDell** [comment]
sorry must be blind or was working off an old directory... could swear I double checked the virtual host file.
