### ISSUE TITLE
Exporting Connection from Child Device Broken

### ISSUE THREAD

**Issue by Payne10** [opendcim/openDCIM#1477]
DCIM Version : 23.02

Normally, exporting connections downloads an excel spread sheet of the device's connections.

Instead it opens a new tab with information looking something like this : object(DevicePorts)#203 (8) { ["DeviceID"]=> int(8077) ["PortNumber"]=> int(-2) ["Label"]=> string(8) "3-4

Clearly the correct information is there, but something is possibly happening with the change to excel part. 

Exporting connections works on parent devices.

**Comment by wilpig** [comment]
can't replicate on current codebase.  closing.
