### ISSUE TITLE
Device Images no longer clickable?

### ISSUE THREAD

**Issue by LFrank2021** [opendcim/openDCIM#1478]
Hi,

with 23.04 the device images are no longer clickable.
In previous version (at least 21.03), a click on the images opened a bigger view of the device images.
Sometimes details were more visible then.
Is the loss of this feature intended or unintended?

Try here https://demo.opendcim.org/devices.php?DeviceID=11

Kind regards
Frank

**Comment by wilpig** [comment]
This is likely related to the jquery update.  I've looked at it just enough to that this on load function isn't firing.

https://github.com/opendcim/openDCIM/blob/master/devices.php#L1310
