### ISSUE TITLE
Drawings link is broken

### ISSUE THREAD

**Issue by lucamaro** [opendcim/openDCIM#1479]
Hello,
I think in db_stats.php line 106 urlencode command break the link url since it contains the path of the image and path separator must not be converted.

```
$mapfile=$config->ParameterArray["drawingpath"] . $dc->DrawingFileName;
...
$mapHTML="<div class=\"canvas\" style=\"background-image: url('".urlencode($mapfile)."')\">
```

**Comment by wilpig** [comment]
https://github.com/opendcim/openDCIM/wiki/FAQ#getting-404-trying-to-access-some-linksimages
