### ISSUE TITLE
Removing CDU impossible...

### ISSUE THREAD

**Issue by heinowalther** [opendcim/openDCIM#1487]
I'm on version 23.04, and have managed to add a CDU via the "Add CDU" button, and now I cannot remove it again...
I can click on the CDU and it shows the PDU I selected, but I do not see any ports or buttons at the bottom where I can remove it again... ?
Here is a screenshot of it...

![Screenshot 2023-12-11 at 00 00 40](https://github.com/opendcim/openDCIM/assets/6001138/bca0853e-e3c4-4418-86f6-c8127b476e03)

Maybe I'm just missing something here?  I'm kinds new to this still...

**Comment by heinowalther** [comment]
I am logged in as the dcim user and I have just tried to create a new CDU which I also cannot delete.
If I add it via the "Add Device" it is also shown under CDU, but it shows all ports and I am able to delete it...
So it is only a problem if I use the "Add CDU"....

**Comment by wilpig** [comment]
Panel pole number was set to A which under PHP8 was not getting converted to zero like in previous versions.  This is a duplicate bug of #1509
