### ISSUE TITLE
Unable to view cabinet inventory

### ISSUE THREAD

**Issue by Decafpancakes** [opendcim/openDCIM#1491]
After getting the application up, I have an issue where the cabinet inventory won't load. I have seen another closed issue regarding this and have adjusted the php.ini file to have the correct time zone as it instructed. However, it seems the issue still persists. Any help would be appreciated, thanks! 

![image](https://github.com/opendcim/openDCIM/assets/69880235/fbb860cd-707d-4127-a4aa-5c3a05033248)

**Comment by wilpig** [comment]
Going to go on the vast information you've provided here to help debug your problem that includes the server logs showing a 500 error when attempting to access the api that you've got something not right.

Since you're running rhel or a red hat derivative you followed the install instructions here to the letter right?  https://github.com/opendcim/openDCIM/wiki/RHEL

My mistake after looking at your bug report I see you're actually running Ubuntu so instead you followed these install instructions to the letter?  https://github.com/opendcim/openDCIM/wiki/Ubuntu

Dangit! My mistake again, you're a sadist running SUSE and you skipped a step here and you're gonna go try again.  https://github.com/opendcim/openDCIM/wiki/OpenSUSE

**Comment by Decafpancakes** [comment]
Ok, I'm running Ubuntu 22.04.3 LTS with the latest version of openDCIM and followed the instructions to the letter several times. What logs would you like and where are they located? Thanks!

**Comment by wilpig** [comment]
You've missed a step.

https://github.com/opendcim/openDCIM/wiki/Ubuntu#ubuntu-2204-installation-instructions

Every single command, to the letter including the webserver configs.  These have been tested on a minimal install and work perfectly when followed.

**Comment by Decafpancakes** [comment]
So, I can upload an image to Device Image Management, however when i try to attach the image to a template it will not let me. 
![image](https://github.com/opendcim/openDCIM/assets/69880235/ef894506-ac5f-4496-aeda-f2ced0d479fe)


When I look at the API URL on the Demo site this is what I see for the cabinets:
![image](https://github.com/opendcim/openDCIM/assets/69880235/72636931-e87f-4bd4-9716-bc3da3f20439)

When I try to look at the same thing on my instance, this is what I get:
![image](https://github.com/opendcim/openDCIM/assets/69880235/dd24b1ec-f82d-476e-a04f-38439bc74b26)

Is the get image request causing the infinite loading squares?

**Comment by wilpig** [comment]
https://github.com/opendcim/openDCIM/wiki/Ubuntu#enable-rewrite-and-ssl-modules-as-well-as-new-opendcim-site-then-restart-apache2-1

**Comment by Decafpancakes** [comment]
That has already been done, I have followed the instructions to a T several times.

**Comment by wilpig** [comment]
Clearly you're getting a 404 so it is evaluating the rewrite rule.

**Comment by Decafpancakes** [comment]
![image](https://github.com/opendcim/openDCIM/assets/69880235/d54f24a9-b9b3-46c4-9751-50baa253adf7)

**Comment by wilpig** [comment]
I've just run through the install from a minimal workstation install just to test and once again, flawless.  You say you followed the direction but you've deviated and I'm going to bet it was here:

https://github.com/opendcim/openDCIM/wiki/Ubuntu#create-opendcim-directories-and-get-application-from-github-1

Did you untar on the system like the install instructions say, or did you scp/rsync  some other file copy mechanism?

**Comment by Decafpancakes** [comment]
I got it figured out, when i was enabling LDAP auth it seems this line “AllowOverride All” got commented out. So now that that’s working, there is also the issue of not being able to delete any racks or DCs, looks like someone else already opened up an issue for that as well.
