### ISSUE TITLE
Project reports in OpenDCIM 23.04 blank web page, no excel

### ISSUE THREAD

**Issue by alex001x** [opendcim/openDCIM#1495]
Hello,

The project reports in OpenDCIM 23.04 that include racks or equipment associated with the project are not functioning properly, resulting in a blank web page and no Excel file available for download. However, when I select a project without any associated racks or equipment, it does provide a downloadable Excel file with a header, a report generated by "user", and notes, but the rest is empty.

Does anyone have an idea to make it work ?
Alex.

**Comment by wilpig** [comment]
I'm not going to go looking at every single report to find one that may trigger this.  Please provide exact steps to reproduce this error and have you tested it on dev.opendcim.org as well to reproduce it?

**Comment by alex001x** [comment]
yes on dev.opendcim.org there is the same problem if associated equipment or rack.

**Comment by alex001x** [comment]
function to handle string ....  is ok THKS @alex001x
