### ISSUE TITLE
The loading of datacenter is endless.

### ISSUE THREAD

**Issue by dionliako** [opendcim/openDCIM#1531]
It seems that it takes a lot of time to load (recreate) navtree or load the dc_stats of the datacenters.
The volume of datacenters is about 10.000 and the cabinets around 100,000.

**Comment by wilpig** [comment]
Yes.  That would happen because to generate the menu it has to load every one of those items which is 100,000+ lines which would make any browser hang.  Don't do ridiculous load testing.

**Comment by dionliako** [comment]
It's not a ridiculous load test. Opendcim is been implemented to a customer and those are the actual data...
