### ISSUE TITLE
URL to image broken in dc_stats.php page

### ISSUE THREAD

**Issue by pa-jberanek** [opendcim/openDCIM#1538]
**Describe the bug**
In the dc_stats.php page, it looks like the URL to the datacentre image is broken

**To Reproduce**
1. Upload an image for a datacentre, and define coordinates for racks etc.
2. Click on the datacentre in the nav par

**Were you able to reproduce this on the dev or demo sites?**
* https://demo.opendcim.org
* https://dev.opendcim.org

No, as I can't upload pictures to the demo sites

**Expected behavior**
Expect to see the datacentre image as configured.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome/Edge

**Additional context**
DCIM 23.04

In dc_stats.php I see:

```
<div><div class="canvas" style="background-image: url('drawings%2Fdc-layouts-th.png')">
	<img src="css/blank.gif" usemap="#datacenter" width="1001" height="607" alt="clearmap over canvas">
	<map name="datacenter" data-dc=1 data-zoom=1 data-x1=0 data-y1=0>
	</map>
	<canvas id="mapCanvas" width="1001" height="607"></canvas>

</div>
```

whereas where I can see the datacentre image in mapmaker.php, I see:

```
<div class="frame" style="margin: 0 0.3em; width: 300px; height: 300px;">
		<img id="map" src="drawings/dc-layouts-th.png">			
    </div> 
```

Notice the "drawings%2F" in the broken page vs. "drawings/" in the working page.

**Comment by wilpig** [comment]
https://github.com/opendcim/openDCIM/wiki/FAQ#getting-404-trying-to-access-some-linksimages

**Comment by pa-jberanek** [comment]
Thank you for the link to the FAQ entry, it worked.
