### ISSUE TITLE
Data Center view not showing Image after upgrade to 23.04 

### ISSUE THREAD

**Issue by razaahmed** [opendcim/openDCIM#1540]
I have upgraded to opendcim 23.04 from 19.01. Everything looks good except the composite view of cabinets that you see when you click on the data center.

Here is what I see in version 19.01
![image](https://github.com/opendcim/openDCIM/assets/2947680/2de89a45-871f-4f25-a80f-74d90ca83098)

Here is what I see in version 23.01

![image](https://github.com/opendcim/openDCIM/assets/2947680/81cca039-0d92-4dec-a5ef-f9de5dce17c3)

I did make sure the file permissions were correct.

**Comment by wilpig** [comment]
https://github.com/opendcim/openDCIM/wiki/FAQ#getting-404-trying-to-access-some-linksimages

**Comment by razaahmed** [comment]
Awesome!! It works
appreciate your quick response.
