### ISSUE TITLE
OpenDcim Upgrade from v19.01 to 23.04

### ISSUE THREAD

**Issue by razaahmed** [opendcim/openDCIM#1544]
This is not a bug, but rather an inquiry about the upgrade process for my production DCIM system. I successfully cloned my production environment and performed an upgrade. However, to switch over to the new DCIM system, I need to update the database.

I attempted to export the database from the current system and import it into the new server, but this process failed. Specifically, I encountered an issue where the ./install.php page appeared blank, with the page title showing "upgrade."

Could you provide guidance or a procedure for correctly exporting and importing the database to complete the upgrade and switch over to the new system?

**Comment by wilpig** [comment]
remove the install.php, and just transfer the db

**Comment by wilpig** [comment]
https://github.com/opendcim/openDCIM/wiki/Upgrade
