### ISSUE TITLE
Storage Room - Dispose of selected devices returning 500 error

### ISSUE THREAD

**Issue by web1452** [opendcim/openDCIM#1545]
**Describe the bug**
When trying to move devices in storage room for each DC, it returns a 500 error message when selecting method of disposal 

**To Reproduce**
1. move device to storage room from rack
2. go to storage room for DC
3. select device in storage room
4. select dispose method and click GO 
5. error 500 appears and device remains in storage room

**Were you able to reproduce this on the dev or demo sites?**
* https://demo.opendcim.org - yes
* https://dev.opendcim.org - no login

**Expected behavior**
Disposed equipment should be removed from Storage Room but not deleted

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Edge
 - Version : 126.0.2592.68

**Comment by wilpig** [comment]
Pretty sure this is already fixed and ready in the next release.  Please verify. 

https://github.com/opendcim/openDCIM/issues/1493
