### ISSUE TITLE
Rack Department overlay in DC map

### ISSUE THREAD

**Issue by crashcartpro** [opendcim/openDCIM#768]
Not sure of the difficulty or desirability of this feature, but I think it'd be a nice view in our environment. 
A rack may already be assigned to a department. so this would paint the department color on the rack.

**Comment by wilpig** [comment]
This has been brought up before and you'd think it would be easy to do but it's not.  The function that paints up the map only knows four colors.  good, bad, getting bad, and wtf did you say to me.  When you pick a status from the drop down it has a list of objects by id and what color to paint them that is restricted to those four values.  I know more JS now and might be able to expand the options but this is currently unfeasible.

**Comment by samilliken** [comment]
Unless someone steps up to take this on, it's not getting done.    After it has been kicked down the road for so long, I'm closing it.
