### ISSUE TITLE
Add names to enclosure bays

### ISSUE THREAD

**Issue by WoMec** [opendcim/openDCIM#869]
It will be very helpfull, if I can add names to enclosure bays (slots). It could also help to solve problem with HP C7000 blade enclosure ( #470  ). You are able to rearrange slots to draw multi-slot devices correctly but there is no match in bays numbers. But if I can rename slot, I can give them right number (name)

**Comment by samilliken** [comment]
You can already draw the slots in any position that you wish.  I don't understand the issue, here.  Clarify or close the issue.

**Comment by WoMec** [comment]
Yes, I know, but for example HP C7000 blade encl. If you position slots in "right" order (1 to 8 in top row and 9 to 16 in bottom row) you are not able to draw multi-slot devices correctly, because they always occupy slots above each other.

But if you position the slots in up-to-down and left-to-right order (green fields in picture), you are able to draw devices correctly, but numbering of slots are wrong. 

Solution of this should be giving a custom name to each slot. After that, you can rename slots to right numbering and you will get good drawing a and also right number of occupied slot.

![dcim-blades cheat-sheet](https://cloud.githubusercontent.com/assets/7909801/25215546/8c27a6ee-259e-11e7-9c63-75dd7f6d5904.PNG)

It looks prety good ... 2-slots and 4-slots devices are corretly drawn
![image](https://cloud.githubusercontent.com/assets/7909801/25215862/3841f12c-25a0-11e7-88d9-c628ec049782.png)

I think, that it could be the same as give custom names to ports on devices or patch panels....

**Comment by WoMec** [comment]
obsolete now - closing
