### ISSUE TITLE
Custom Attributes issues

### ISSUE THREAD

**Issue by samilliken** [opendcim/openDCIM#908]
In further testing of v4.4 we found the following behaviour with Custom Attributes:

1. If you set a Custom Attribute in the Configuration page with a default value, the value is no longer populated when creating a new device

2. If you have set a value for a Custom Attribute on a Device Template it is no longer populated when using that template on a new device.

**Comment by dmbanke** [comment]
Some clarification on this. In scenario 1 and 2 above not only is it not showing for new devices but it no longer shows for devices previously created. It appears the value from the default and/or template is no longer being read and displayed on the Device screen. I also checked this behaviour in 18.01. This is the major reason we have not moved our Production from v4.3. We use a custom attribute of System Name to separate out the components used by different areas of the department. It was primarily populated using templates.

**Comment by vinod-wagh** [comment]
Hello Everyone,
Some clarification I am using OpenDCIM-4.5 and find out the custom attribute values get fetch in reports but for the parent devices not for the child devices.
